name: makeanyicon
description: Command-line Interface (CLI) for any_icon_maker.
version: 0.1.0
homepage: https://github.com/makeanyicon/makeanyicon

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  any_icon_maker: ^0.1.0
  args: ^2.2.0
  image: ^3.0.5
  yaml: ^3.1.0

# dependency_overrides:
#   any_icon_maker:
#     path: ../any_icon_maker

executables:
  makeanyicon: main
