name: any_icon_maker
description: A configurable icon maker.
version: 0.1.0
homepage: https://github.com/makeanyicon/any_icon_maker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image: ^3.0.5
